import type {
  Project,
  BoqItem,
  WbsNode,
  Activity,
  ActivityLink,
  Resource,
  ActivityResource,
  BudgetLine,
  Risk,
  Issue,
  ProgressUpdate,
  CostTransaction,
  ProcurementSubmittal,
} from '@/types';

export function getInitialSeedData() {
  const projectId = 'proj-seed-001';
  const now = '2026-09-01T08:00:00Z';
  const startDate = '2026-09-15';
  const endDate = '2027-04-30';
  const dataDate = '2026-11-15';

  const project: Project = {
    id: projectId,
    name: 'مشروع إنشاء مبنى مكاتب تجاري (4 أدوار) - الرياض',
    client: 'شركة الأفق للاستثمار العقاري',
    location: 'الرياض - حي الياسمين',
    contract_value: 2345150,
    currency: 'SAR',
    start_date: startDate,
    end_date: endDate,
    data_date: dataDate,
    status_logic: 'retained_logic',
    duration_days: 195,
    status: 'active',
    calendar_type: '6_days',
    sector: 'commercial_building',
    description: 'مشروع إنشاء وتشطيب مبنى مكتبي متكامل يشمل الأعمال الإنشائية والمعمارية والكهروميكانيكية.',
    created_at: now,
  };

  const project2: Project = {
    id: 'proj-seed-002',
    name: 'مشروع إنشاء طريق سريع وشبكات تصريف (15 كم) - الشرقية',
    client: 'وزارة النقل والخدمات اللوجستية',
    location: 'المنطقة الشرقية - طريق الدمام الجبيل',
    contract_value: 48000000,
    currency: 'SAR',
    start_date: '2026-08-01',
    end_date: '2027-10-30',
    data_date: '2026-11-15',
    status_logic: 'retained_logic',
    duration_days: 450,
    status: 'active',
    calendar_type: '6_days',
    sector: 'infrastructure_highway',
    description: 'مشروع إنشاء طريق مزدوج بطول 15 كم مع جسور تقاطعات وشبكات تصريف سيول وإنارة ذكية.',
    created_at: now,
  };

  const project3: Project = {
    id: 'proj-seed-003',
    name: 'مشروع مجمع مستشفى تخصصي 200 سرير - جدة',
    client: 'شركة الرعاية الطبية المتقدمة',
    location: 'جدة - حي الشاطئ',
    contract_value: 85000000,
    currency: 'SAR',
    start_date: '2026-06-01',
    end_date: '2028-02-28',
    data_date: '2026-11-15',
    status_logic: 'retained_logic',
    duration_days: 620,
    status: 'active',
    calendar_type: '6_days',
    sector: 'healthcare_hospital',
    description: 'مشروع إنشاء وتجهيز مستشفى تخصصي متكامل يشمل غرف العمليات والعناية المركزة وأنظمة الغازات الطبية.',
    created_at: now,
  };

  const project4: Project = {
    id: 'proj-seed-004',
    name: 'مشروع مجمع فلل سكنية راقية (50 فيلا) - الرياض',
    client: 'صندوق التطوير العقاري السكني',
    location: 'الرياض - حي النرجس',
    contract_value: 32500000,
    currency: 'SAR',
    start_date: '2026-07-15',
    end_date: '2027-08-30',
    data_date: '2026-11-15',
    status_logic: 'retained_logic',
    duration_days: 410,
    status: 'active',
    calendar_type: '6_days',
    sector: 'residential_complex',
    description: 'إنشاء 50 فيلا سكنية فاخرة مع أعمال البنية التحتية والحدائق وشبكات الصرف والري.',
    created_at: now,
  };

  const boqItems: BoqItem[] = [
    { id: 'boq-01', project_id: projectId, code: 'EW-001', description: 'حفريات الموقع العام ونقل المخلفات', unit: 'm3', quantity: 1200, unit_price: 35, total_price: 42000, category: 'Earthworks', section: '01 أعمال الموقع', sort_order: 1, created_at: now },
    { id: 'boq-02', project_id: projectId, code: 'EW-002', description: 'أعمال الردم بطبقات ورش المياه والدمك', unit: 'm3', quantity: 450, unit_price: 45, total_price: 20250, category: 'Earthworks', section: '01 أعمال الموقع', sort_order: 2, created_at: now },
    { id: 'boq-03', project_id: projectId, code: 'CW-001', description: 'خرسانة نظافة عادية أسفل القواعد', unit: 'm3', quantity: 95, unit_price: 420, total_price: 39900, category: 'Concrete Works', section: '02 الخرسانات', sort_order: 3, created_at: now },
    { id: 'boq-04', project_id: projectId, code: 'CW-002', description: 'خرسانة مسلحة للقواعد والميد الأرضية', unit: 'm3', quantity: 280, unit_price: 680, total_price: 190400, category: 'Foundations', section: '02 الخرسانات', sort_order: 4, created_at: now },
    { id: 'boq-05', project_id: projectId, code: 'RS-001', description: 'حديد تسليح للقواعد والأعمدة', unit: 'ton', quantity: 45, unit_price: 2950, total_price: 132750, category: 'Reinforcement Steel', section: '02 الخرسانات', sort_order: 5, created_at: now },
    { id: 'boq-06', project_id: projectId, code: 'CW-003', description: 'خرسانة مسلحة للأعمدة والأسقف لجميع الأدوار', unit: 'm3', quantity: 650, unit_price: 720, total_price: 468000, category: 'Concrete Works', section: '02 الخرسانات', sort_order: 6, created_at: now },
    { id: 'boq-07', project_id: projectId, code: 'MS-001', description: 'مباني بلك إسمنتي معزول وخفيف للجدران', unit: 'm2', quantity: 3200, unit_price: 95, total_price: 304000, category: 'Masonry', section: '03 المعماري', sort_order: 7, created_at: now },
    { id: 'boq-08', project_id: projectId, code: 'RF-001', description: 'أعمال العزل المائي والحراري للأسطح', unit: 'm2', quantity: 850, unit_price: 160, total_price: 136000, category: 'Roofing & Insulation', section: '03 المعماري', sort_order: 8, created_at: now },
    { id: 'boq-09', project_id: projectId, code: 'PL-001', description: 'أعمال اللياسة الداخلية والخارجية', unit: 'm2', quantity: 6400, unit_price: 42, total_price: 268800, category: 'Plastering', section: '03 المعماري', sort_order: 9, created_at: now },
    { id: 'boq-10', project_id: projectId, code: 'TL-001', description: 'توريد وتركيب بورسلان وسيراميك للأرضيات', unit: 'm2', quantity: 2400, unit_price: 185, total_price: 444000, category: 'Tiling & Flooring', section: '03 المعماري', sort_order: 10, created_at: now },
    { id: 'boq-11', project_id: projectId, code: 'EL-001', description: 'أعمال التمديدات الكهربائية واللوحات والإنارة', unit: 'point', quantity: 820, unit_price: 185, total_price: 151700, category: 'Electrical', section: '04 الكهروميكانيك', sort_order: 11, created_at: now },
    { id: 'boq-12', project_id: projectId, code: 'HV-001', description: 'توريد وتركيب وحدات التكييف المركزي VRF', unit: 'unit', quantity: 50, unit_price: 2947, total_price: 147350, category: 'HVAC', section: '04 الكهروميكانيك', sort_order: 12, created_at: now },
  ];

  const wbsNodes: WbsNode[] = [
    { id: 'wbs-01', project_id: projectId, parent_id: null, code: '1.0', name: 'أعمال الموقع والأساسات', level: 1, sort_order: 1, boq_item_id: null, created_at: now },
    { id: 'wbs-02', project_id: projectId, parent_id: null, code: '2.0', name: 'الهيكل الخرساني الرئيسي', level: 1, sort_order: 2, boq_item_id: null, created_at: now },
    { id: 'wbs-03', project_id: projectId, parent_id: null, code: '3.0', name: 'الأعمال المعمارية والتشطيبات', level: 1, sort_order: 3, boq_item_id: null, created_at: now },
    { id: 'wbs-04', project_id: projectId, parent_id: null, code: '4.0', name: 'الأعمال الكهروميكانيكية (MEP)', level: 1, sort_order: 4, boq_item_id: null, created_at: now },
  ];

  const activities: Activity[] = [
    {
      id: 'act-01',
      project_id: projectId,
      wbs_node_id: 'wbs-01',
      code: 'ACT-100',
      name: 'تسليم الموقع وبدء أعمال الحفر',
      early_start: '2026-09-15',
      early_finish: '2026-09-26',
      late_start: '2026-09-15',
      late_finish: '2026-09-26',
      duration_days: 10,
      planned_quantity: 1200,
      actual_quantity: 1200,
      unit: 'm3',
      percent_complete: 100,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: '2026-09-15',
      actual_finish: '2026-09-25',
      sort_order: 1,
      total_float: 0,
      free_float: 0,
      activity_drag: 10,
      discipline: 'Civil',
      contractor: 'شركة الرمال للحفريات',
      created_at: now,
    },
    {
      id: 'act-02',
      project_id: projectId,
      wbs_node_id: 'wbs-01',
      code: 'ACT-110',
      name: 'صب خرسانة النظافة والعزل المائي للقواعد',
      early_start: '2026-09-27',
      early_finish: '2026-10-04',
      late_start: '2026-09-27',
      late_finish: '2026-10-04',
      duration_days: 7,
      planned_quantity: 95,
      actual_quantity: 95,
      unit: 'm3',
      percent_complete: 100,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: '2026-09-27',
      actual_finish: '2026-10-03',
      sort_order: 2,
      total_float: 0,
      free_float: 0,
      activity_drag: 7,
      discipline: 'Civil',
      contractor: 'طاقم المقاول العام',
      created_at: now,
    },
    {
      id: 'act-03',
      project_id: projectId,
      wbs_node_id: 'wbs-01',
      code: 'ACT-120',
      name: 'تسليح وصب القواعد المسلحة ورقاب الأعمدة',
      early_start: '2026-10-05',
      early_finish: '2026-10-22',
      late_start: '2026-10-05',
      late_finish: '2026-10-22',
      duration_days: 15,
      planned_quantity: 280,
      actual_quantity: 280,
      unit: 'm3',
      percent_complete: 100,
      percent_complete_type: 'physical',
      constraint_type: 'SNET',
      constraint_date: '2026-10-05',
      is_critical: true,
      is_milestone: false,
      actual_start: '2026-10-05',
      actual_finish: '2026-10-20',
      sort_order: 3,
      total_float: 0,
      free_float: 0,
      activity_drag: 15,
      discipline: 'Civil',
      contractor: 'طاقم المقاول العام',
      created_at: now,
    },
    {
      id: 'act-04',
      project_id: projectId,
      wbs_node_id: 'wbs-01',
      code: 'ACT-130',
      name: 'عزل القواعد والردم والدمك على طبقات',
      early_start: '2026-10-23',
      early_finish: '2026-11-01',
      late_start: '2026-10-25',
      late_finish: '2026-11-03',
      duration_days: 8,
      planned_quantity: 450,
      actual_quantity: 360,
      unit: 'm3',
      percent_complete: 80,
      percent_complete_type: 'physical',
      is_critical: false,
      is_milestone: false,
      actual_start: '2026-10-23',
      actual_finish: null,
      sort_order: 4,
      total_float: 2,
      free_float: 2,
      activity_drag: 0,
      discipline: 'Civil',
      contractor: 'شركة الرمال للحفريات',
      created_at: now,
    },
    {
      id: 'act-05',
      project_id: projectId,
      wbs_node_id: 'wbs-02',
      code: 'ACT-200',
      name: 'صب أعمدة وسقف الدور الأرضي',
      early_start: '2026-11-02',
      early_finish: '2026-11-21',
      late_start: '2026-11-02',
      late_finish: '2026-11-21',
      duration_days: 17,
      planned_quantity: 160,
      actual_quantity: 110,
      unit: 'm3',
      percent_complete: 65,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: '2026-11-02',
      actual_finish: null,
      sort_order: 5,
      total_float: 0,
      free_float: 0,
      activity_drag: 17,
      discipline: 'Structural',
      contractor: 'طاقم المقاول العام',
      created_at: now,
    },
    {
      id: 'act-06',
      project_id: projectId,
      wbs_node_id: 'wbs-02',
      code: 'ACT-210',
      name: 'صب أعمدة وسقف الدور الأول والمتكرر',
      early_start: '2026-11-22',
      early_finish: '2026-12-20',
      late_start: '2026-11-22',
      late_finish: '2026-12-20',
      duration_days: 24,
      planned_quantity: 320,
      actual_quantity: 0,
      unit: 'm3',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: null,
      actual_finish: null,
      sort_order: 6,
      total_float: 0,
      free_float: 0,
      activity_drag: 24,
      discipline: 'Structural',
      contractor: 'طاقم المقاول العام',
      created_at: now,
    },
    {
      id: 'act-07',
      project_id: projectId,
      wbs_node_id: 'wbs-03',
      code: 'ACT-300',
      name: 'أعمال المباني والبلك لجميع الأدوار',
      early_start: '2026-12-10',
      early_finish: '2027-01-15',
      late_start: '2026-12-15',
      late_finish: '2027-01-20',
      duration_days: 30,
      planned_quantity: 3200,
      actual_quantity: 0,
      unit: 'm2',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: false,
      is_milestone: false,
      actual_start: null,
      actual_finish: null,
      sort_order: 7,
      total_float: 5,
      free_float: 5,
      activity_drag: 0,
      discipline: 'Architectural',
      contractor: 'مؤسسة البناء الحديث',
      created_at: now,
    },
    {
      id: 'act-08',
      project_id: projectId,
      wbs_node_id: 'wbs-04',
      code: 'ACT-400',
      name: 'التمديدات الكهربائية والصحية الأولية',
      early_start: '2026-12-22',
      early_finish: '2027-01-25',
      late_start: '2026-12-22',
      late_finish: '2027-01-25',
      duration_days: 28,
      planned_quantity: 820,
      actual_quantity: 0,
      unit: 'point',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: null,
      actual_finish: null,
      sort_order: 8,
      total_float: 0,
      free_float: 0,
      activity_drag: 28,
      discipline: 'MEP',
      contractor: 'شركة الأنظمة الكهروميكانيكية',
      created_at: now,
    },
    {
      id: 'act-09',
      project_id: projectId,
      wbs_node_id: 'wbs-03',
      code: 'ACT-310',
      name: 'اللياسة والتشطيبات الداخلية والأسطح',
      early_start: '2027-01-26',
      early_finish: '2027-03-10',
      late_start: '2027-01-26',
      late_finish: '2027-03-10',
      duration_days: 38,
      planned_quantity: 6400,
      actual_quantity: 0,
      unit: 'm2',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: null,
      actual_finish: null,
      sort_order: 9,
      total_float: 0,
      free_float: 0,
      activity_drag: 38,
      discipline: 'Architectural',
      contractor: 'مؤسسة البناء الحديث',
      created_at: now,
    },
    {
      id: 'act-10',
      project_id: projectId,
      wbs_node_id: 'wbs-04',
      code: 'ACT-410',
      name: 'تركيب أنظمة التكييف والإنارة والتشغيل النهائي',
      early_start: '2027-03-11',
      early_finish: '2027-04-20',
      late_start: '2027-03-11',
      late_finish: '2027-04-20',
      duration_days: 34,
      planned_quantity: 48,
      actual_quantity: 0,
      unit: 'unit',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: false,
      actual_start: null,
      actual_finish: null,
      sort_order: 10,
      total_float: 0,
      free_float: 0,
      activity_drag: 34,
      discipline: 'MEP',
      contractor: 'شركة الأنظمة الكهروميكانيكية',
      created_at: now,
    },
    {
      id: 'act-11',
      project_id: projectId,
      wbs_node_id: 'wbs-03',
      code: 'MS-500',
      name: 'معلم الإنجاز النهائي والتسليم الابتدائي',
      early_start: '2027-04-20',
      early_finish: '2027-04-20',
      late_start: '2027-04-20',
      late_finish: '2027-04-20',
      duration_days: 0,
      planned_quantity: 1,
      actual_quantity: 0,
      unit: 'item',
      percent_complete: 0,
      percent_complete_type: 'physical',
      is_critical: true,
      is_milestone: true,
      milestone_type: 'finish',
      constraint_type: 'MFO',
      constraint_date: '2027-04-20',
      actual_start: null,
      actual_finish: null,
      sort_order: 11,
      total_float: 0,
      free_float: 0,
      activity_drag: 0,
      discipline: 'Management',
      contractor: 'الإدارة الهندسية',
      created_at: now,
    },
  ];

  const activityLinks: ActivityLink[] = [
    { id: 'lnk-01', project_id: projectId, predecessor_id: 'act-01', successor_id: 'act-02', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-02', project_id: projectId, predecessor_id: 'act-02', successor_id: 'act-03', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-03', project_id: projectId, predecessor_id: 'act-03', successor_id: 'act-04', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-04', project_id: projectId, predecessor_id: 'act-03', successor_id: 'act-05', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-05', project_id: projectId, predecessor_id: 'act-05', successor_id: 'act-06', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-06', project_id: projectId, predecessor_id: 'act-05', successor_id: 'act-07', link_type: 'SS', lag_days: 10 },
    { id: 'lnk-07', project_id: projectId, predecessor_id: 'act-06', successor_id: 'act-08', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-08', project_id: projectId, predecessor_id: 'act-08', successor_id: 'act-09', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-09', project_id: projectId, predecessor_id: 'act-09', successor_id: 'act-10', link_type: 'FS', lag_days: 0 },
    { id: 'lnk-10', project_id: projectId, predecessor_id: 'act-10', successor_id: 'act-11', link_type: 'FS', lag_days: 0 },
  ];

  const resources: Resource[] = [
    { id: 'res-01', project_id: projectId, name: 'فريق الحفر والآليات الثقيلة', type: 'equipment', unit: 'يومية', unit_rate: 3500, availability: 2, ownership: 'rental', created_at: now },
    { id: 'res-02', project_id: projectId, name: 'طاقم نجارة وحدادة مسلحة', type: 'labor', unit: 'طاقم/يوم', unit_rate: 2200, availability: 4, ownership: 'company', created_at: now },
    { id: 'res-03', project_id: projectId, name: 'مضخة خرسانة وخلاطات', type: 'equipment', unit: 'm3', unit_rate: 45, availability: 1, ownership: 'subcontractor', created_at: now },
    { id: 'res-04', project_id: projectId, name: 'طاقم مباني ولياسة معمارية', type: 'labor', unit: 'طاقم/يوم', unit_rate: 1800, availability: 3, ownership: 'company', created_at: now },
    { id: 'res-05', project_id: projectId, name: 'فنيو كهروميكانيك وتكييف', type: 'labor', unit: 'يومية', unit_rate: 650, availability: 6, ownership: 'company', created_at: now },
  ];

  const activityResources: ActivityResource[] = [
    { id: 'ar-01', project_id: projectId, activity_id: 'act-01', resource_id: 'res-01', planned_quantity: 10, actual_quantity: 10, created_at: now },
    { id: 'ar-02', project_id: projectId, activity_id: 'act-02', resource_id: 'res-02', planned_quantity: 7, actual_quantity: 7, created_at: now },
    { id: 'ar-03', project_id: projectId, activity_id: 'act-03', resource_id: 'res-02', planned_quantity: 15, actual_quantity: 15, created_at: now },
    { id: 'ar-04', project_id: projectId, activity_id: 'act-05', resource_id: 'res-02', planned_quantity: 17, actual_quantity: 12, created_at: now },
    { id: 'ar-05', project_id: projectId, activity_id: 'act-07', resource_id: 'res-04', planned_quantity: 30, actual_quantity: 0, created_at: now },
    { id: 'ar-06', project_id: projectId, activity_id: 'act-08', resource_id: 'res-05', planned_quantity: 28, actual_quantity: 0, created_at: now },
  ];

  const budgetLines: BudgetLine[] = [
    { id: 'bgt-01', project_id: projectId, wbs_node_id: 'wbs-01', boq_item_id: 'boq-01', description: 'أعمال الحفريات ونقل المخلفات', planned_cost: 42000, committed_cost: 42000, actual_cost: 40500, remaining_cost: 1500, created_at: now },
    { id: 'bgt-02', project_id: projectId, wbs_node_id: 'wbs-01', boq_item_id: 'boq-03', description: 'خرسانات النظافة والقواعد والميد', planned_cost: 250550, committed_cost: 250550, actual_cost: 242000, remaining_cost: 8550, created_at: now },
    { id: 'bgt-03', project_id: projectId, wbs_node_id: 'wbs-02', boq_item_id: 'boq-06', description: 'الهيكل الخرساني والحديد للأدوار المتكررة', planned_cost: 600750, committed_cost: 580000, actual_cost: 395000, remaining_cost: 205750, created_at: now },
    { id: 'bgt-04', project_id: projectId, wbs_node_id: 'wbs-03', boq_item_id: 'boq-07', description: 'المباني واللياسة والعزل والتشطيبات', planned_cost: 1152800, committed_cost: 600000, actual_cost: 20000, remaining_cost: 1132800, created_at: now },
    { id: 'bgt-05', project_id: projectId, wbs_node_id: 'wbs-04', boq_item_id: 'boq-11', description: 'أنظمة الكهروميكانيك والتكييف والإنارة', planned_cost: 299050, committed_cost: 150000, actual_cost: 12000, remaining_cost: 287050, created_at: now },
  ];

  const risks: Risk[] = [
    { id: 'rsk-01', project_id: projectId, title: 'تأخر توريد وحدات التكييف المركزي VRF من المصنع', description: 'احتمال تأخر الشحن البحري لوحدات التكييف الرئيسية لمدة 3 أسابيع.', probability: 3, impact: 4, severity: 12, mitigation: 'التنسيق مع المورد لتأكيد تاريخ الشحن مبكراً وحجز دفعات من المخزون المحلي.', status: 'open', category: 'Procurement', identified_date: '2026-09-05', created_at: now },
    { id: 'rsk-02', project_id: projectId, title: 'تذبذب أسعار حديد التسليح والخرسانة الجاهزة', description: 'ارتفاع محتمل في أسعار المواد الأساسية خلال الربع الأول.', probability: 2, impact: 3, severity: 6, mitigation: 'تثبيت أسعار التوريد بعقود مسبقة مع مصانع الخرسانة وموردي الحديد.', status: 'open', category: 'Financial', identified_date: '2026-09-02', created_at: now },
    { id: 'rsk-03', project_id: projectId, title: 'صعوبة التربة ووجود مياه جوفية عند الحفر العميق', description: 'احتمالية ظهور مياه جوفية تتطلب نظام نزح مستمر.', probability: 2, impact: 4, severity: 8, mitigation: 'تجهيز مضخات نزح مياه احتياطية بالموقع وتأمين شبكة تصريف سريعة.', status: 'mitigated', category: 'Site', identified_date: '2026-09-01', created_at: now },
  ];

  const issues: Issue[] = [
    { id: 'iss-01', project_id: projectId, title: 'تعديل مسارات دكت التكييف في الدور الأول لتعارضها مع الجسور', description: 'وجود تعارض طفيف بين مسار مجاري الهواء وجسر خرساني ساقط.', status: 'in_progress', priority: 'high', proposed_solution: 'إعادة تصميم فتحات الجسور واعتماد مخططات Shop Drawings المحدثة.', assignee: 'م. أحمد خالد (مهندس الموقع)', raised_date: '2026-10-15', resolved_date: null, created_at: now },
  ];

  const progressUpdates: ProgressUpdate[] = [
    { id: 'prg-01', project_id: projectId, activity_id: 'act-01', update_date: '2026-09-25', percent_complete: 100, actual_quantity: 1200, quantity_to_date: 1200, status: 'approved', approved_at: '2026-09-25T16:00:00Z', rejected_reason: null, notes: 'تم اكتمال أعمال الحفر واستلام المنسوب بنجاح.', created_at: now },
    { id: 'prg-02', project_id: projectId, activity_id: 'act-02', update_date: '2026-10-03', percent_complete: 100, actual_quantity: 95, quantity_to_date: 95, status: 'approved', approved_at: '2026-10-03T17:00:00Z', rejected_reason: null, notes: 'صب خرسانة النظافة بنجاح بعد استلام حديد التسليح.', created_at: now },
    { id: 'prg-03', project_id: projectId, activity_id: 'act-03', update_date: '2026-10-20', percent_complete: 100, actual_quantity: 280, quantity_to_date: 280, status: 'approved', approved_at: '2026-10-20T18:00:00Z', rejected_reason: null, notes: 'تم صب القواعد المسلحة بالكامل واعتماد تقارير كسر المكعبات.', created_at: now },
    { id: 'prg-04', project_id: projectId, activity_id: 'act-05', update_date: '2026-11-15', percent_complete: 65, actual_quantity: 110, quantity_to_date: 110, status: 'approved', approved_at: '2026-11-15T15:00:00Z', rejected_reason: null, notes: 'انتهاء أعمال نجارة وحدادة سقف الدور الأرضي وجاري التحضير للصب.', created_at: now },
  ];

  const costTransactions: CostTransaction[] = [
    { id: 'cst-01', project_id: projectId, activity_id: 'act-01', boq_item_id: 'boq-01', category: 'Earthworks', transaction_date: '2026-09-25', description: 'مستخلص مقاول الحفريات ونقل المخلفات', cost_type: 'direct', amount: 40500, source: 'invoice', status: 'approved', approved_at: '2026-09-26T10:00:00Z', rejected_reason: null, invoice_number: 'INV-2026-001', vendor: 'شركة الرمال للحفريات', created_at: now },
    { id: 'cst-02', project_id: projectId, activity_id: 'act-02', boq_item_id: 'boq-03', category: 'Concrete Works', transaction_date: '2026-10-03', description: 'توريد وصب خرسانة نظافة عادية', cost_type: 'direct', amount: 39900, source: 'invoice', status: 'approved', approved_at: '2026-10-04T09:00:00Z', rejected_reason: null, invoice_number: 'INV-2026-002', vendor: 'مصنع الشرق للخرسانة', created_at: now },
    { id: 'cst-03', project_id: projectId, activity_id: 'act-03', boq_item_id: 'boq-04', category: 'Concrete Works', transaction_date: '2026-10-20', description: 'توريد خرسانة وحديد تسليح القواعد', cost_type: 'direct', amount: 184100, source: 'invoice', status: 'approved', approved_at: '2026-10-21T11:00:00Z', rejected_reason: null, invoice_number: 'INV-2026-003', vendor: 'مجموعة الراجحي للصناعة', created_at: now },
    { id: 'cst-04', project_id: projectId, activity_id: 'act-05', boq_item_id: 'boq-06', category: 'Concrete Works', transaction_date: '2026-11-15', description: 'دفعة صب أعمدة وسقف الدور الأرضي', cost_type: 'direct', amount: 245000, source: 'invoice', status: 'approved', approved_at: '2026-11-16T14:00:00Z', rejected_reason: null, invoice_number: 'INV-2026-004', vendor: 'مصنع الشرق للخرسانة', created_at: now },
    { id: 'cst-05', project_id: projectId, activity_id: 'act-06', boq_item_id: 'boq-06', category: 'Concrete Works', transaction_date: '2026-11-15', description: 'دفعة حديد تسليح وخلاطات جاهزة الدور الأول', cost_type: 'direct', amount: 200000, source: 'invoice', status: 'approved', approved_at: '2026-11-16T15:00:00Z', rejected_reason: null, invoice_number: 'INV-2026-005', vendor: 'شركة حديد سابك', created_at: now },
  ];

  const procurementSubmittals: ProcurementSubmittal[] = [
    {
      id: 'sub-01',
      project_id: projectId,
      activity_id: 'act-03',
      code: 'SD-STR-001',
      title: 'مخططات الورشة التنفيذية لحديد تسليح القواعد ورقاب الأعمدة (Shop Drawings)',
      type: 'shop_drawing',
      supplier_or_subcontractor: 'المكتب الهندسي الاستشاري',
      submittal_date: '2026-09-18',
      required_approval_date: '2026-10-01',
      actual_approval_date: '2026-09-30',
      lead_time_days: 12,
      status: 'approved',
      is_critical_path: true,
      notes: 'تم الاعتماد بنجاح بدون ملاحظات جوهرية.',
      created_at: now,
    },
    {
      id: 'sub-02',
      project_id: projectId,
      activity_id: 'act-05',
      code: 'MAT-CONC-002',
      title: 'اعتماد خلطة الخرسانة الجاهزة المقاومة C35 للأعمدة والأسقف',
      type: 'material_submittal',
      supplier_or_subcontractor: 'مصنع الشرق للخرسانة الجاهزة',
      submittal_date: '2026-10-10',
      required_approval_date: '2026-10-25',
      actual_approval_date: '2026-10-24',
      lead_time_days: 14,
      status: 'approved',
      is_critical_path: true,
      notes: 'تمت مطابقة نتائج اختبارات الشد والضغط القياسية.',
      created_at: now,
    },
    {
      id: 'sub-03',
      project_id: projectId,
      activity_id: 'act-10',
      code: 'LL-VRF-003',
      title: 'توريد وحدات التكييف المركزي VRF والملحقات (Long-Lead Procurement)',
      type: 'long_lead_item',
      supplier_or_subcontractor: 'شركة التكييف العالمية المحدودة',
      submittal_date: '2026-10-20',
      required_approval_date: '2026-11-10',
      actual_approval_date: '2026-11-08',
      lead_time_days: 90,
      status: 'approved_with_notes',
      is_critical_path: true,
      notes: 'مدة التصنيع والشحن 90 يوماً ويجب متابعة جدول الشحنات البحرية.',
      created_at: now,
    },
    {
      id: 'sub-04',
      project_id: projectId,
      activity_id: 'act-09',
      code: 'MAT-TL-004',
      title: 'عينات واعتماد بلاط البورسلان والسيراميك للأرضيات والجدران',
      type: 'material_submittal',
      supplier_or_subcontractor: 'شركة الخزف السعودية',
      submittal_date: '2026-11-05',
      required_approval_date: '2026-11-20',
      actual_approval_date: null,
      lead_time_days: 20,
      status: 'under_review',
      is_critical_path: false,
      notes: 'قيد مراجعة واعتماد المالك والاستشاري.',
      created_at: now,
    },
  ];

  return {
    projects: [project, project2, project3, project4],
    boq_items: boqItems,
    wbs_nodes: wbsNodes,
    activities,
    activity_links: activityLinks,
    resources,
    activity_resources: activityResources,
    budget_lines: budgetLines,
    risks,
    issues,
    progress_updates: progressUpdates,
    cost_transactions: costTransactions,
    procurement_submittals: procurementSubmittals,
    project_baselines: [
      { id: 'bsl-01', project_id: projectId, baseline_name: 'خط الأساس المعتمد تعاقدياً (Target 1 - Rev 0)', is_active: true, status: 'approved', created_at: now },
      { id: 'bsl-02', project_id: projectId, baseline_name: 'خط الأساس المحدث رقم 1 (Target 2 - Rev 1)', is_active: false, status: 'approved', created_at: now },
    ],
    baseline_activities: activities.map((act) => ({
      id: `ba-${act.id}`,
      baseline_id: 'bsl-01',
      activity_id: act.id,
      early_start: act.early_start || startDate,
      early_finish: act.early_finish || endDate,
      duration_days: act.duration_days,
      planned_cost: act.planned_quantity * 100,
    })),
    project_alerts: [],
    forecast_snapshots: [],
    recovery_snapshots: [],
    scenario_simulations: [],
    inspection_requests: [
      {
        id: 'wir-01',
        project_id: projectId,
        request_number: 'WIR-CIV-001',
        boq_item_id: 'boq-01',
        activity_id: 'act-01',
        parent_reference: 'MIR-EW-01',
        inspection_date: '2026-09-25',
        inspected_quantity: 1200,
        approved_quantity: 1200,
        status: 'approved',
        inspector: 'م. حسام الاستشاري',
        notes: 'تم فحص مناسيب قاع الحفر واختبار الدمك بنجاح ومطابقة المخططات.',
        approved_at: '2026-09-25T16:00:00Z',
        approved_by: 'Resident Engineer',
        rejected_reason: null,
        created_at: now,
        executor_type: 'self_direct',
        client_unit_rate: 45,
        client_earned_value: 54000,
      },
      {
        id: 'wir-02',
        project_id: projectId,
        request_number: 'WIR-CONC-002',
        boq_item_id: 'boq-03',
        activity_id: 'act-02',
        parent_reference: 'MIR-CONC-02',
        inspection_date: '2026-10-03',
        inspected_quantity: 95,
        approved_quantity: 95,
        status: 'approved',
        inspector: 'م. حسام الاستشاري',
        notes: 'استلام نجارة وحدادة وصب خرسانة النظافة ومطابقة نتائج المكعبات.',
        approved_at: '2026-10-03T17:00:00Z',
        approved_by: 'Resident Engineer',
        rejected_reason: null,
        created_at: now,
        executor_type: 'subcontractor',
        subcontractor_id: 'SUB-PKG-01',
        subcontractor_name: 'شركة البنيان لأعمال الخرسانات والهياكل',
        zone_or_scope: 'الأساسات المركزية',
        subcontract_unit_rate: 350,
        client_unit_rate: 480,
        subcontractor_cost: 33250,
        client_earned_value: 45600,
        profit_margin_sar: 12350,
      },
      {
        id: 'wir-03',
        project_id: projectId,
        request_number: 'WIR-CONC-003',
        boq_item_id: 'boq-04',
        activity_id: 'act-03',
        parent_reference: 'MIR-CONC-03',
        inspection_date: '2026-10-20',
        inspected_quantity: 220,
        approved_quantity: 220,
        status: 'approved',
        inspector: 'م. حسام الاستشاري',
        notes: 'استلام حديد تسليح القواعد ورقاب الأعمدة بالقطاع A واعتماد تقارير الصب.',
        approved_at: '2026-10-20T18:00:00Z',
        approved_by: 'Resident Engineer',
        rejected_reason: null,
        created_at: now,
        executor_type: 'subcontractor',
        subcontractor_id: 'SUB-PKG-01',
        subcontractor_name: 'شركة البنيان لأعمال الخرسانات والهياكل',
        zone_or_scope: 'القطاع A (Zone A - البرج الرئيسي)',
        subcontract_unit_rate: 380,
        client_unit_rate: 550,
        subcontractor_cost: 83600,
        client_earned_value: 121000,
        profit_margin_sar: 37400,
      },
      {
        id: 'wir-04',
        project_id: projectId,
        request_number: 'WIR-CONC-004',
        boq_item_id: 'boq-06',
        activity_id: 'act-05',
        parent_reference: 'MIR-CONC-05',
        inspection_date: '2026-11-15',
        inspected_quantity: 110,
        approved_quantity: 110,
        status: 'approved',
        inspector: 'م. حسام الاستشاري',
        notes: 'استلام حديد تسليح سقف الدور الأرضي ومطابقة أقطار ومسافات الكانات قبل الصب.',
        approved_at: '2026-11-15T15:00:00Z',
        approved_by: 'Resident Engineer',
        rejected_reason: null,
        created_at: now,
        executor_type: 'subcontractor',
        subcontractor_id: 'SUB-PKG-01',
        subcontractor_name: 'شركة البنيان لأعمال الخرسانات والهياكل',
        zone_or_scope: 'سقف الأرضي والأول (القطاع A)',
        subcontract_unit_rate: 370,
        client_unit_rate: 590,
        subcontractor_cost: 40700,
        client_earned_value: 64900,
        profit_margin_sar: 24200,
      },
      {
        id: 'wir-05',
        project_id: projectId,
        request_number: 'WIR-MEP-005',
        boq_item_id: 'boq-07',
        activity_id: 'act-10',
        parent_reference: 'MIR-HVAC-01',
        inspection_date: '2026-11-20',
        inspected_quantity: 450,
        approved_quantity: 0,
        status: 'submitted',
        inspector: 'م. وليد استشاري الكهروميكانيك',
        notes: 'طلب استلام وفحص دكت الصاج المجلفن والعوازل للدور الأول - قيد المراجعة الموقعية.',
        approved_at: null,
        approved_by: null,
        rejected_reason: null,
        created_at: now,
        executor_type: 'subcontractor',
        subcontractor_id: 'SUB-PKG-03',
        subcontractor_name: 'مؤسسة الدقة لأعمال التكييف ومجاري الهواء (HVAC)',
        zone_or_scope: 'دكت الدور الأول والملحقات',
        subcontract_unit_rate: 95,
        client_unit_rate: 145,
        subcontractor_cost: 42750,
        client_earned_value: 65250,
        profit_margin_sar: 22500,
      },
    ],
  };
}
